version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: felipezln/node_app
    ports:
      - "2020:2020"
    environment:
      - PG_DB=node_crud_db
      - PG_USER=felipe
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    volumes:
      - ./:/app

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_crud_db
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}